# Crea una imagen de Squid sobre de Alpine Linux. Se definen dos variables
# de compilación que, si son utilizadas, permiten indicar las versiones de 
# Alpine Linux y Squid a utilizar.
#   ALPINE_VERSION:     Versión de Alpine Linux.
#   SQUID_VERSION:      Versión de Squid.
# De forma predeterminada instala Squid 6.6-r0 sobre alpine:latest
ARG ALPINE_VERSION=latest

# hadolint ignore=DL3007
FROM "alpine:$ALPINE_VERSION"

ENV container docker

LABEL maintainer="Javier Gómez <gpjavierjob@gmail.com>"

COPY files/uid-entrypoint.sh /usr/local/bin/

ARG SQUID_VERSION=6.6-r0

# hadolint ignore=DL3018
RUN apk "--no-cache" "add" "ca-certificates" "squid=$SQUID_VERSION" "tzdata" \
    && chmod 755 /usr/local/bin/uid-entrypoint.sh \
    && mkdir -p /etc/squid/conf.d /var/log/squid /var/cache/squid \
    && chgrp -R 0 /var/log/squid /var/cache/squid \
    && chmod -R g=u /etc/passwd /var/log/squid /var/cache/squid

ENV TZ=UTC

COPY files/squid.conf /etc/squid/
COPY files/snippet.conf /etc/squid/conf.d/

ENTRYPOINT ["uid-entrypoint.sh"]

USER 10010
EXPOSE 3128
CMD ["squid", "-N"]
