"""empty message

Revision ID: 354427f48b8c
Revises: e51d34f198ae
Create Date: 2024-05-07 17:44:25.410156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354427f48b8c'
down_revision = 'e51d34f198ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('client_server_id_name_index', ['server_id', 'name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('client_server_id_name_index')

    op.drop_table('clients')
    # ### end Alembic commands ###
