"""empty message

Revision ID: 4ebb3dcffc24
Revises: cc6e47c7dda8
Create Date: 2024-06-03 16:32:36.221998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebb3dcffc24'
down_revision = 'cc6e47c7dda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    op.drop_table('auto')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(), nullable=True))

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    op.create_table('auto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('archived', sa.BOOLEAN(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
