"""empty message

Revision ID: 801c6e329924
Revises: 4b8675708f4f
Create Date: 2024-05-29 16:25:00.560946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801c6e329924'
down_revision = '4b8675708f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
