"""empty message

Revision ID: 886630ee0b79
Revises: 5d1a03e153a2
Create Date: 2024-04-24 16:38:29.448781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886630ee0b79'
down_revision = '5d1a03e153a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('errmsg', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('errmsg')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
