"""empty message

Revision ID: cf25dce93503
Revises: 8f05ece6a383
Create Date: 2024-05-29 16:31:20.107139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf25dce93503'
down_revision = '8f05ece6a383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_clients')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('client_server_id_email_index', ['server_id', 'email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('client_server_id_email_index')

    op.create_table('_alembic_tmp_clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('server_id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('errmsg', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
